name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t hocvv111999/tele-miniapp:latest .
          docker push hocvv111999/tele-miniapp:latest

  deployment:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy to EC2
    steps:
      - uses: actions/checkout@v3

      - name: Execute SSH commands on remote server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > keypair.pem && chmod 600 keypair.pem
          ssh -o StrictHostKeyChecking=no -i keypair.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
          sh ~/accomy-fe/deploy-accomy-fe.sh'
